import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        
          <main className="flex w-full flex-col  justify-center px-8 text-center">{children}</main>
        
      </body>
    </html>
  );
}
